version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: delivery/Dockerfile
    container_name: app
    entrypoint:
      [
        "app/wait-for-it.sh", "-t", "0", "api:8080", "--",
        "app/wait-for-it.sh", "-t", "0", "redis:6379", "--",
        "java", "-jar", "/app/chore-management-bot.jar"
      ]
    environment:
      - API_BASE_URL=http://api:8080
      - ADMIN_API_KEY
      - TELEGRAM_BOT_TOKEN
      - TELEGRAM_BOT_USERNAME
      - TELEGRAM_CREATOR_ID
      - USERS_CACHE=false
      - LOG_LEVEL=DEBUG
      - REDIS_HOST=redis

  api:
    image: sralloza/chore-management-api:$API_VERSION
    container_name: api
    environment:
      - ADMIN_API_KEY=dd67df5a-5c40-4b73-a9ec-0c34c9bf3cac
      - APPLICATION_SECRET=whatever
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_HOST=database
      - DATABASE_PORT=3306
      - DATABASE_NAME=chore-management
      - WAIT_FOR_IT_ADDRESS=database:3306
    ports:
      - "8080:8080"

  database:
    image: mysql:oracle
    container_name: database
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=chore-management
    ports:
      - "3306:3306"

  redis:
    image: redis:6.2.6
    container_name: redis
    ports:
      - "6379:6379"

  provision:
    build:
      context: .
      dockerfile: scripts/provision-data/Dockerfile
    container_name: provision
    entrypoint:
      [
        "delivery/wait-for-it.sh", "-t", "0", "api:8080", "--",
        "scripts/provision-data/run.sh", "http://api:8080"
      ]
    volumes:
      - ./scripts:/scripts
      - ./delivery:/delivery
      - ./.env:/.env
