name: E2E tests

on:
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      POETRY_VIRTUALENVS_CREATE: "false"
      TERM: xterm-color
    steps:
      - uses: actions/checkout@v2

      - name: Build app to run unit tests
        run: docker-compose build app
